import Head from 'next/head';
import EventDetailsMain from '../../components/EventDetails/EventDetailsMain';
import Footer from '../../components/Layouts/Footer/Default/Footer';
import HeaderFour from '../../components/Layouts/Header/HeaderFour/HeaderFour';

export default function EventDetails() {

  return (
    <>
      <Head>
        <title>Eduman - Education And Online Courses React, NextJs Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       
      <HeaderFour />
      <EventDetailsMain />
      <Footer />
    </>
  )
}
