import Head from 'next/head';
import InstructorProMain from '../../components/InstructorProfile/InstructorProMain';
import Footer from '../../components/Layouts/Footer/Default/Footer';
import HeaderFour from '../../components/Layouts/Header/HeaderFour/HeaderFour';


export default function InstructorProfile() {

  return (
    <>
      <Head>
        <title>Eduman - Education And Online Courses React, NextJs Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeaderFour />
      <InstructorProMain />
      <Footer />
    </>
  )
}
