import Head from 'next/head';
import FaqDetailsMain from '../../components/FaqDetails/FaqDetailsMain';
import Footer from '../../components/Layouts/Footer/Default/Footer';
import HeaderFour from '../../components/Layouts/Header/HeaderFour/HeaderFour';

export default function FaqDetails() {

  return (
    <>
      <Head>
        <title>Eduman - Education And Online Courses React, NextJs Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       
      <HeaderFour />
      <FaqDetailsMain />
      <Footer />
    </>
  )
}